fun main(args: Array<String>) {
    val rbTree = AVLTree<Int, String>()
    rbTree.insert(1, "fuck")
    rbTree.insert(2, "shit")
    rbTree.insert(666, "hell")
    rbTree.insert(4, "sucker")
    rbTree.insert(8, "nuts")
    rbTree.print()
    println()
    rbTree.insert(5, "NYA")
    rbTree.insert(6, "LOL")
    rbTree.insert(7, "WHY")
    rbTree.print()
    println()
    println(rbTree.parentsCorrectness())
}
